/**
 * @file llm.ts
 * @module src/providers/llm
 * @author Dominic Rodemer
 * @created 2025-12-21
 * @license MIT
 *
 * @fileoverview LLM.js wrapper for AI provider communication.
 */

import LLM from '@themaximalist/llm.js';

import type { Provider, RiskLevel } from '../config/schema.js';
import { RISK_LEVELS } from '../config/schema.js';
import type { SystemInfo } from '../system/detector.js';
import { configManager } from '../config/manager.js';
import { PROVIDER_ENV_VAR_NAMES } from '../config/defaults.js';
import { promptBuilder } from '../prompts/builder.js';
import { wrapError } from '../utils/errors.js';

export type { RiskLevel } from '../config/schema.js';

/** A command generated by the AI provider. */
export interface GeneratedCommand {
    /** The shell command to execute. */
    command: string;
    /** Brief description of what the command does. */
    description: string;
    /** Detailed explanation of the command components. */
    explanation: string;
    /** Risk level assessment for the command. */
    risk: RiskLevel;
}

/** Options for command generation. */
export interface GenerateOptions {
    /** AI provider to use (overrides default). */
    provider?: Provider;
    /** Model to use (overrides default). */
    model?: string;
    /** Number of commands to generate. */
    count?: number;
}

/** Raw response structure from LLM.js. */
interface LLMResponse {
    /** Array of generated commands. */
    commands: GeneratedCommand[];
}

/**
 * Handles communication with AI providers via LLM.js.
 * Generates shell commands from natural language prompts.
 */
export class LLMProvider {
    /**
     * Generates shell commands from a natural language prompt.
     * @param prompt - The user's natural language request.
     * @param systemInfo - Current system environment information.
     * @param options - Generation options (provider, model, count).
     * @returns Array of generated commands with descriptions and risk levels.
     * @throws Error if no API key is configured or AI call fails.
     */
    async generateCommands(
        prompt: string,
        systemInfo: SystemInfo,
        options: GenerateOptions = {},
    ): Promise<GeneratedCommand[]> {
        const provider = options.provider || configManager.get('defaultProvider');
        const model = options.model || configManager.get('defaultModel');
        const count = options.count || configManager.getPreference('commandCount');

        const apiKey = configManager.getApiKey(provider);
        if (!apiKey) {
            throw new Error(
                `No API key configured for provider: ${provider}. Run 'clai config wizard' to set it up.`,
            );
        }

        const systemPrompt = promptBuilder.buildSystemPrompt(systemInfo, count);
        const userPrompt = promptBuilder.buildUserPrompt(prompt);

        // Set the API key in environment for LLM.js
        this.setApiKeyEnv(provider, apiKey);

        const modelIdentifier = this.getModelIdentifier(provider, model);

        try {
            // Combine system prompt and user prompt as messages
            const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;

            // Use LLM.js with JSON parser
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const response = await (LLM as any)(fullPrompt, {
                model: modelIdentifier,
                parser: (LLM as { parsers: { json: unknown } }).parsers.json,
            });

            return this.parseResponse(response as unknown as LLMResponse);
        } catch (error) {
            throw wrapError(error, 'Failed to generate commands');
        }
    }

    private setApiKeyEnv(provider: Provider, apiKey: string): void {
        process.env[PROVIDER_ENV_VAR_NAMES[provider]] = apiKey;
    }

    private getModelIdentifier(provider: Provider, model: string): string {
        // LLM.js uses specific prefixes for different providers
        const providerPrefixes: Record<Provider, string> = {
            openai: '',
            anthropic: 'anthropic:',
            gemini: 'google:',
            groq: 'groq:',
        };

        return `${providerPrefixes[provider]}${model}`;
    }

    private parseResponse(response: LLMResponse): GeneratedCommand[] {
        if (!response || !response.commands || !Array.isArray(response.commands)) {
            throw new Error('Invalid response format from AI');
        }

        return response.commands.map((cmd) => ({
            command: cmd.command || '',
            description: cmd.description || '',
            explanation: cmd.explanation || '',
            risk: this.validateRisk(cmd.risk),
        }));
    }

    private validateRisk(risk: string): RiskLevel {
        if (RISK_LEVELS.includes(risk as RiskLevel)) {
            return risk as RiskLevel;
        }
        return 'medium'; // Default to medium if unknown
    }
}

/** Singleton LLMProvider instance. */
export const llmProvider = new LLMProvider();
